name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  spack-install-and-test:
    name: Install and Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/access-nri/build-ci-runner:rocky-v0.22
      volumes:
      - upstream-data:/dev/null:ro
    services:
      upstream:
        image: ghcr.io/access-nri/build-ci-runner:rocky-v0.22
        volumes:
        - upstream-data:/dev/null:rw
    steps:
    - run: tree /opt/upstream